server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/users/**

        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**

        - id: transaction-service
          uri: ${TRANSACTION_SERVICE_URL}
          predicates:
            - Path=/api/transactions/**

        - id: wallet-service
          uri: ${WALLET_SERVICE_URL}
          predicates:
            - Path=/api/v1/wallets/**

        - id: reward-service
          uri: ${REWARD_SERVICE_URL}
          predicates:
            - Path=/api/rewards/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL}
          predicates:
            - Path=/api/notify/**